# https://goreleaser.com
project_name: wantarr

# Build
builds:
  -
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X "build.Version={{ .Version }}"
      - -X "build.GitCommit={{ .ShortCommit }}"
      - -X "build.Timestamp={{ .Timestamp }}"
    flags:
      - -trimpath

# Archive
archives:
  -
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: "tar.gz"

# Checksum
checksum:
  name_template: "checksums.txt"
  algorithm: sha512

# Snapshot
snapshot:
  name_template: "{{ .Tag }}+{{ .ShortCommit }}"

# Changelog
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
