image:
  - Ubuntu1804
  - macOS
  - Visual Studio 2019
platform: x64

branches:
  only:
    - master
    - develop

artifacts:
  - path: dist

install:
  - go version
  - go env
  - cinst make
  - cinst mingw
  - make vendor

build_script:
  - make build