image: Ubuntu1804

platform: x64

branches:
  only:
    - master
    - develop

artifacts:
  - path: dist/*

install:
  - go version
  - go env
  - echo $PATH
  - make vendor

build_script:
  - make build