image: Ubuntu1804

platform: x64

branches:
  only:
    - master
    - develop

install:
  - go version
  - go env
  - echo $PATH
  - go get github.com/karalabe/xgo

build_script:
  - xgo -targets='linux/amd64,darwin/amd64,windows/amd64' /home/appveyor/projects/wantarr