image:
  - Ubuntu1804
  - macOS

platform: x64

branches:
  only:
    - master
    - develop

artifacts:
  - path: '*.tgz'
    name: wantarr

install:
  - go version
  - go env
  - make vendor

build_script:
  - make build
  - build=$(find dist/* -type d | sed 's!.*/!!'); cd dist/$build; tar -czf $build.tgz wantarr