image: Ubuntu1804

platform: x64

branches:
  only:
    - master
    - develop

#clone_folder: c:\gopath\src\github.com\l3uddz\wantarr
clone_folder: /root/src/github.com/l3uddz/wantarr

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env

build_script:
  - make build-all