image:
  - Ubuntu1804
  - macOS

platform: x64

branches:
  only:
    - master
    - develop

artifacts:
  - path: dist/**

install:
  - go version
  - go env
  - make vendor

build_script:
  - make build