image:
  - Ubuntu1804
  - macOS

platform: x64

branches:
  only:
    - master
    - develop

deploy:
  - provider: GitHub
    auth_token:
      secure: japCKJyRSrHvPJV0hqZZGcRM9ZSR9GsTVh8SCCwbqiyuKTyB3OCcRMc6ICztczfV
    artifact: wantarr
    force_update: true

artifacts:
  - path: dist/**/*.tar.tgz
    name: wantarr

install:
  - go version
  - go env
  - make vendor

build_script:
  - make build
  - export build=$(find dist/* -type d | sed 's!.*/!!')
  - cd dist/$build
  - tar -czf $build.tar.tgz wantarr
